/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'sector-pages': SectorPage;
    whitepapers: Whitepaper;
    references: Reference;
    'blog-posts': BlogPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'sector-pages': SectorPagesSelect<false> | SectorPagesSelect<true>;
    whitepapers: WhitepapersSelect<false> | WhitepapersSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'career-page': CareerPage;
    'team-page': TeamPage;
    'network-page': NetworkPage;
    'whitepaper-page': WhitepaperPage;
    'blog-page': BlogPage;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'career-page': CareerPageSelect<false> | CareerPageSelect<true>;
    'team-page': TeamPageSelect<false> | TeamPageSelect<true>;
    'network-page': NetworkPageSelect<false> | NetworkPageSelect<true>;
    'whitepaper-page': WhitepaperPageSelect<false> | WhitepaperPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-pages".
 */
export interface SectorPage {
  id: number;
  title: string;
  /**
   * z.B. "verwaltung", "gesundheitswesen", "kirche"
   */
  slug: string;
  hero: {
    /**
     * Kann Zeilenumbrüche enthalten (\n)
     */
    title: string;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  intro?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Mehrzeilige Beschreibung (\n\n für Absätze)
     */
    description?: string | null;
  };
  sections?:
    | {
        title: string;
        items?:
          | {
              title: string;
              description?: string | null;
              actionType?: ('brochure' | 'contact' | 'link') | null;
              actionLabel?: string | null;
              actionUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  network?: {
    title?: string | null;
    description?: string | null;
    linkUrl?: string | null;
    linkLabel?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whitepapers".
 */
export interface Whitepaper {
  id: number;
  title: string;
  description: string;
  type: 'whitepaper' | 'podcast' | 'omnia';
  pdfUrl?: string | null;
  pdfFile?: (number | null) | Media;
  podcastUrl?: string | null;
  /**
   * z.B. "OMNIA" für OMNIA-Produkte
   */
  category?: string | null;
  featured?: boolean | null;
  /**
   * Niedrigere Zahlen werden zuerst angezeigt
   */
  order?: number | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  name: string;
  title: string;
  company?: string | null;
  quote: string;
  image?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * Hervorgehobene Referenzen werden prominenter angezeigt
   */
  featured?: boolean | null;
  /**
   * Niedrigere Zahlen werden zuerst angezeigt
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-freundlicher Name (z.B. "digitalisierung-in-der-verwaltung")
   */
  slug: string;
  /**
   * Kurze Zusammenfassung für Vorschau (max. 200 Zeichen)
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author?: string | null;
  categories?:
    | ('digitalisierung' | 'verwaltung' | 'gesundheitswesen' | 'kirche' | 'ki-technologie' | 'news' | 'events')[]
    | null;
  publishedAt?: string | null;
  /**
   * Artikel auf der Blog-Übersicht hervorheben
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Überschreibt den Seitentitel für Suchmaschinen (max. 60 Zeichen)
     */
    metaTitle?: string | null;
    /**
     * Beschreibung für Suchmaschinen (max. 160 Zeichen)
     */
    metaDescription?: string | null;
    /**
     * Bild für Social Media Shares (1200x630px empfohlen)
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sector-pages';
        value: number | SectorPage;
      } | null)
    | ({
        relationTo: 'whitepapers';
        value: number | Whitepaper;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-pages_select".
 */
export interface SectorPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  intro?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              actionType?: T;
              actionLabel?: T;
              actionUrl?: T;
              id?: T;
            };
        id?: T;
      };
  network?:
    | T
    | {
        title?: T;
        description?: T;
        linkUrl?: T;
        linkLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whitepapers_select".
 */
export interface WhitepapersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  pdfUrl?: T;
  pdfFile?: T;
  podcastUrl?: T;
  category?: T;
  featured?: T;
  order?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  company?: T;
  quote?: T;
  image?: T;
  logo?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  categories?: T;
  publishedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  threePillars?: {
    title?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          icon?: (number | null) | Media;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          title: string;
          tagline?: string | null;
          description?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    title?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    subtitle?: string | null;
    buttonText?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  address?: {
    street?: string | null;
    zip?: string | null;
    city?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  email?: string | null;
  registry?: {
    court?: string | null;
    number?: string | null;
    taxNumber?: string | null;
    vatId?: string | null;
  };
  ceo?: string | null;
  agbPdfUrl?: string | null;
  odrLink?: string | null;
  disputeResolutionText?: string | null;
  contactPerson?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  bookingUrl?: string | null;
  newsletterTitle?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterButtonLabel?: string | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'facebook' | 'instagram' | 'youtube' | 'xing';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-page".
 */
export interface CareerPage {
  id: number;
  intro?: {
    title?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  benefits?:
    | {
        title: string;
        description?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  expectations?: {
    title?: string | null;
    description?: string | null;
  };
  jobOpenings?:
    | {
        title: string;
        description?: string | null;
        callToAction?: string | null;
        additionalText?: string | null;
        tasks?:
          | {
              task?: string | null;
              id?: string | null;
            }[]
          | null;
        profile?:
          | {
              requirement?: string | null;
              id?: string | null;
            }[]
          | null;
        jobBenefits?:
          | {
              benefit?: string | null;
              id?: string | null;
            }[]
          | null;
        pdfUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page".
 */
export interface TeamPage {
  id: number;
  intro?: {
    title?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  members?:
    | {
        name: string;
        role: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  departments?:
    | {
        title: string;
        description?: string | null;
        email?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  values?: {
    intro?: {
      title?: string | null;
      subtitle?: string | null;
    };
    items?:
      | {
          title: string;
          subtitle?: string | null;
          description?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-page".
 */
export interface NetworkPage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    description?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  about?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  visionMission?: {
    title?: string | null;
    description?: string | null;
  };
  solutions?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  topics?: {
    title?: string | null;
    fields?:
      | {
          id: string;
          title: string;
          icon?: (number | null) | Media;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whitepaper-page".
 */
export interface WhitepaperPage {
  id: number;
  hero?: {
    title?: string | null;
    intro?: string | null;
  };
  form?: {
    title?: string | null;
    note?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
  };
  intro?: string | null;
  seo?: {
    /**
     * Überschreibt den Seitentitel für Suchmaschinen (max. 60 Zeichen)
     */
    metaTitle?: string | null;
    /**
     * Beschreibung für Suchmaschinen (max. 160 Zeichen)
     */
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  impressum?: {
    title?: string | null;
    /**
     * Vollständiger Impressum-Text mit Firmendaten, Registerdaten, etc.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  datenschutz?: {
    title?: string | null;
    /**
     * Vollständige Datenschutzerklärung gemäß DSGVO.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  widerruf?: {
    title?: string | null;
    /**
     * Widerrufsbelehrung für Verbraucher.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  threePillars?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              link?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              tagline?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonText?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  address?:
    | T
    | {
        street?: T;
        zip?: T;
        city?: T;
        country?: T;
      };
  phone?: T;
  email?: T;
  registry?:
    | T
    | {
        court?: T;
        number?: T;
        taxNumber?: T;
        vatId?: T;
      };
  ceo?: T;
  agbPdfUrl?: T;
  odrLink?: T;
  disputeResolutionText?: T;
  contactPerson?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  bookingUrl?: T;
  newsletterTitle?: T;
  newsletterPlaceholder?: T;
  newsletterButtonLabel?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-page_select".
 */
export interface CareerPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  expectations?:
    | T
    | {
        title?: T;
        description?: T;
      };
  jobOpenings?:
    | T
    | {
        title?: T;
        description?: T;
        callToAction?: T;
        additionalText?: T;
        tasks?:
          | T
          | {
              task?: T;
              id?: T;
            };
        profile?:
          | T
          | {
              requirement?: T;
              id?: T;
            };
        jobBenefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
        pdfUrl?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  members?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  departments?:
    | T
    | {
        title?: T;
        description?: T;
        email?: T;
        icon?: T;
        id?: T;
      };
  values?:
    | T
    | {
        intro?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        items?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-page_select".
 */
export interface NetworkPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        backgroundImage?: T;
      };
  about?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  visionMission?:
    | T
    | {
        title?: T;
        description?: T;
      };
  solutions?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  topics?:
    | T
    | {
        title?: T;
        fields?:
          | T
          | {
              id?: T;
              title?: T;
              icon?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whitepaper-page_select".
 */
export interface WhitepaperPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  form?:
    | T
    | {
        title?: T;
        note?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  intro?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  impressum?:
    | T
    | {
        title?: T;
        content?: T;
      };
  datenschutz?:
    | T
    | {
        title?: T;
        content?: T;
      };
  widerruf?:
    | T
    | {
        title?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}